### ISSUE TITLE
Can we expect multithreaded rendering and higher frame rates in a future update?

### ISSUE THREAD

**Issue by ChristophGeske** [google-ar/arcore-unity-sdk#141]
Booth these features might solve the problems we encounter when trying to build a better GearVR/Daydream app using ARCore for tracking the head movement in 6DoF.

**Comment by pablisho** [comment]
Hi, Thanks for the feature request. Multithreading rendering is a feature requested by many developers, but I cannot share any timelines right now.
If you need a higher frame rate, I believe you can change the configuration [MatchCameraFramerate](https://github.com/google-ar/arcore-unity-sdk/blob/master/Assets/GoogleARCore/SDK/Scripts/ARCoreSessionConfig.cs#L37) to false, that way you won't be stuck to 30 FPS for the rendering of your objects, animations, etc., although the background will still be updated at 30 FPS.
Stay tuned for future releases!

**Comment by eisenbruch** [comment]
Can confirm that multithreaded rendering would help dramatically to reliably run an AR session and record the device's screen at the same time. Some Galaxy S7s can't run my app smoothly when I have the recording capabilities baked in, and multithreaded rendering would solve this. The recording plugin (NatCorder) is built for multi threaded rendering anyway.

**Comment by ChristophGeske** [comment]
I build a workaround which improves the issue of only having 30fps and allows me to run games in 60fps even in VR.  
For 60fps I do the following: 
I record the position data I receive from the camera and spread it over two quicker frames. For that I use Vector3.Lerp(pos, goal ,0.5f); . This way I introduce half a frame of lag because I don't update to the right position immediately. It turns out this is not even noticeable in VR. Which is great for my application. 
I would prefer to get the full 60fps so I can get back my half frame but for know I am happy with the improvements.

**Comment by andrelevi** [comment]
+1 Hoping for more information about multithreading and a 60fps camera.

**Comment by small-potatoes** [comment]
We heard your feedback!  Multithreaded rendering is now supported with the ARCore SDK when using Unity 2017.4f9+ :)

**Comment by ChrisBeswick** [comment]
> We heard your feedback! Multithreaded rendering is now supported with the ARCore SDK when using Unity 2017.4f9+ :)

Hey, Do you have any ETA on this? 
Cheers!

**Comment by olokobayusuf** [comment]
@small-potatoes Thank you! I'm the developer of [NatCorder](https://medium.com/@olokobayusuf/natcorder-unity-recording-made-easy-f0fdee0b5055) and I was just about to offer to help you guys implement multithreaded rendering. Devs trying to record ARCore gameplay will significantly benefit from this.

**Comment by mathiassiig** [comment]
@small-potatoes or @olokobayusuf  Can you elaborate? On Unity 2018.1 with Unity ARCore SDK version 1.6, but still getting the same "ARCore Does Not Support Multi-threaded Rendering" error when trying to build with multi-threaded rendering enabled.

**Comment by mdurand42** [comment]
Mike from Unity here. We implemented support for multi-threaded rendering in 2018.2 and backported it to 2017.4 which is one of our Long Term Support (LTS) versions. We did not (and won't) backport it to 2018.1 since the expectation is that any user of 2018.1 would upgrade to 2018.2. 

You can read more about how our releases work here: https://blogs.unity3d.com/2018/04/09/new-plans-for-unity-releases-introducing-the-tech-and-long-term-support-lts-streams/

**Comment by ARportals** [comment]
Hi,

The multi-threading option still does not work in Unity 2020.2.3f1. The documentation still says to disable the Multi-threading option and when I tried to enable it, my phone (Samsung S7) says that it's not compatible anymore and the AR does not work.

Any update on this? I'm getting 13-18 fps when recording

**Comment by ARportals** [comment]
Any news on that?

**Comment by olokobayusuf** [comment]
> Hi,
> 
> The multi-threading option still does not work in Unity 2020.2.3f1. The documentation still says to disable the Multi-threading option and when I tried to enable it, my phone (Samsung S7) says that it's not compatible anymore and the AR does not work.
> 
> Any update on this? I'm getting 13-18 fps when recording

How are you recording video if I may ask? If you use NatCorder, then there's a [WIP extension package](https://github.com/natsuite/NatCorder-Performance-Extensions) that provides async GPU readbacks on OpenGL ES, giving you recording performance comparable to that of Vulkan.

**Comment by mimming** [comment]
This is fixed!

> The multi-threading option still does not work in Unity 2020.2.3f1. The documentation still says to disable the Multi-threading option and when I tried to enable it, my phone (Samsung S7) says that it's not compatible anymore and the AR does not work.

I suspect something else may be going on.  What version of the ARCore Unity SDK are you using?  When it does not work, do you see any error messages or events in the app log?

**Comment by ARportals** [comment]
Your right! After testing again, it's working now!

**Comment by mimming** [comment]
> Your right! After testing again, it's working now!

Glad to hear!
