### ISSUE TITLE
ARBackground shader for Linear color space

### ISSUE THREAD

**Issue by NicolasWipon** [google-ar/arcore-unity-sdk#268]
Hello,

When we use Linear color space instead of Gamma color space, the colors from camera feed are brighter.
In ARKit, there are 2 shaders used for the ARBackground : one for gamma and one for linear with a gamma-to-linear conversion.

I duplicated the ARBackground shader and change it to create a Linear version of this shader and it solved the problem.

So this is not really an issue anymore but I share the shader with you in case of you are interested to add it in your package. I made the change only in the subshader for GLES3 below the  _//gamma to linear conversion_ comment.

There it is : 

```
Shader "Custom/ARCore/ARBackground(Linear)"
{
    Properties {
        _MainTex ("Texture", 2D) = "white" {}
        _UvTopLeftRight ("UV of top corners", Vector) = (0, 1, 1, 1)
        _UvBottomLeftRight ("UV of bottom corners", Vector) = (0 , 0, 1, 0) 
    }

    // For GLES3
    SubShader
    {
        Pass
        {
            ZWrite Off

            GLSLPROGRAM

            #pragma only_renderers gles3

            #ifdef SHADER_API_GLES3
            #extension GL_OES_EGL_image_external_essl3 : require
            #endif

            uniform vec4 _UvTopLeftRight;
            uniform vec4 _UvBottomLeftRight;

            #ifdef VERTEX

            varying vec2 textureCoord;

            void main()
            {
                #ifdef SHADER_API_GLES3
                vec2 uvTop = mix(_UvTopLeftRight.xy, _UvTopLeftRight.zw, gl_MultiTexCoord0.x);
                vec2 uvBottom = mix(_UvBottomLeftRight.xy, _UvBottomLeftRight.zw, gl_MultiTexCoord0.x);
                textureCoord = mix(uvTop, uvBottom, gl_MultiTexCoord0.y);

                gl_Position = gl_ModelViewProjectionMatrix * gl_Vertex;
                #endif
            }

            #endif

            #ifdef FRAGMENT
            varying vec2 textureCoord;
            uniform samplerExternalOES _MainTex;

            void main()
            {
                #ifdef SHADER_API_GLES3
                gl_FragColor = texture(_MainTex, textureCoord);
                //gamma to linear conversion
		gl_FragColor.rgb = pow(gl_FragColor.rgb, vec3(2.2));
                #endif
            }

            #endif

            ENDGLSL
        }
    }

  Subshader
  {
    Pass
    {
      ZWrite Off

      CGPROGRAM

      #pragma exclude_renderers gles3
      #pragma vertex vert
      #pragma fragment frag

      #include "UnityCG.cginc"

      uniform float4 _UvTopLeftRight;
      uniform float4 _UvBottomLeftRight;

      struct appdata
      {
        float4 vertex : POSITION;
        float2 uv : TEXCOORD0;
      };

      struct v2f
      {
        float2 uv : TEXCOORD0;
        float4 vertex : SV_POSITION;
      };

      v2f vert(appdata v)
      {
        float2 uvTop = lerp(_UvTopLeftRight.xy, _UvTopLeftRight.zw, v.uv.x);
        float2 uvBottom = lerp(_UvBottomLeftRight.xy, _UvBottomLeftRight.zw, v.uv.x);

        v2f o;
        o.vertex = UnityObjectToClipPos(v.vertex);
        o.uv = lerp(uvTop, uvBottom, v.uv.y);

        // Instant preview's texture is transformed differently.
        o.uv = o.uv.yx;
        o.uv.x = 1.0 - o.uv.x;

        return o;
      }

      sampler2D _MainTex;

      fixed4 frag(v2f i) : SV_Target
      {
           return tex2D(_MainTex, i.uv);
      }
      ENDCG
    }
  }

  FallBack Off
}
```

Just put it in a material and reference the material in "Background Material" propertie of ARCoreBackgroundRenderer component on the camera.

**Comment by pablisho** [comment]
Hi, thanks for the feature request and for proposing a solution.

**Comment by philmaas** [comment]
yes ios is too bright and android is too dark because of colorspaces ?!
also it doesn't seem to change anything, eventhough I place the correct linear materials on both AR cameras?
Project should be set to linear or is the preprocess build of the sample app changing it automatically to gamma?

**Comment by NicolasWipon** [comment]
Hi,

In Player Settings>Other Settings, you have a Color Space property.

If you set Color Space to Gamma :  

- on iOS : you should use YUVMaterial (set it on UnityARVideo component placed on the Camera game object, for 'Clear Material' property). 
- on Android : you should use ARBackground material of ARCore.

If you set Color Space to Linear : 

- on iOS : you should use YUVMaterialLinear (it is included in ARKit package by default).
- on Android : you should use the ARBackground(Linear) shader I proposed (create a material, set its shader to Custom/ARCore/ARBackground(Linear) and put this material in 'Background Material' property of the ARCoreBackgroundRenderer component on the Camera game object.

For Android, the shader I proposed works only for GLES3 Graphic API. 

If you are using YUVMaterial (for iOS) and ARBackground material (for ARCore) in Linear Color Space, the colors of the camera will be too bright (you can compare with the Camera app of your smartphone to see the difference).

**Comment by fredsa** [comment]
Fixed in 1.9.0
https://github.com/google-ar/arcore-unity-sdk/releases

**Comment by Olivier50** [comment]
In ARCore, the colors are steal brighter in linear color space with the new sdk release...

**Comment by indikman** [comment]
The issue still remain in ARFoundation 2.1.1 with ARCore and ARKit latest. The camera input looks washed and highly grained.
