### ISSUE TITLE
AR core camera freezes when we switch to some other camera and return back!

### ISSUE THREAD

**Issue by NavinAJ** [google-ar/arcore-unity-sdk#374]
Hi guys,

I'm trying to switch cameras in Unity with ARcore integrated. The swap is between AR camera and Unity normal camera. when the switch is done from ARcam to normal unity cam everything works fine but when I return back to tracking with ARcam ( switch fromNormal cam to AR cam) I witnessed AR cam was frozen and was not tracking the plane anymore. is there a way to pause and resume tracking on camera switch in unity ARcore ? can someone help me with it?

**Comment by pablisho** [comment]
Hi @NavinAJ. You can pause and resume the session/tracking by disabling/enabling the ARSession component. Let me know if this helps.

**Comment by NavinAJ** [comment]
Thanks, Pablisho. That solved my problem.

**Comment by pablisho** [comment]
Cool! I'm closing this as your question was solved.

**Comment by Aaditya009** [comment]
Hello,
I have this exact same problem. However, I do disable/enable the ARSession object. But the problem still remains. I'm using Unity 2018.3.12f1. Any help is appreciated.

**Comment by indracs97** [comment]
having the same problem but using the android sdk version, what should i do?
