### ISSUE TITLE
Anchor does not work on iOS 12 and iPhone X or iPad

### ISSUE THREAD

**Issue by JeanVACCA** [google-ar/arcore-unity-sdk#398]
Since i have updated to iOS 12 ; I m no more able to host or resolve anchor. (ErrorInternal)

I have no problem with my iPhone 6s but with iPad (6th gen) and iPhone X that doesn't work anymore.

Thank for your help.

**Comment by pablisho** [comment]
Hi, thanks for the report. @sammcd any ideas?

**Comment by sammcd** [comment]
Thanks for reporting this!

I'm fairly certain this is caused by a bug that we fixed in 1.4. Could you update the SDK and try again?

Thanks!

**Comment by JeanVACCA** [comment]
We use the latest version : 1.4.1

**Comment by JeanVACCA** [comment]
I have juste tested the 1.5.0 version; but the issue is still here:

`
ErrorInternal
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
UnityEngine.MonoBehaviour:print(Object)
<_ResolveAnchorFromId>c__AnonStorey6:<>m__0(CloudAnchorResult)
System.Action`1:Invoke(T)
GoogleARCore.<AsyncTask>c__AnonStorey0:<>m__0()
System.Action:Invoke()
GoogleARCore.AsyncTask:OnUpdate()
System.Action:Invoke()
GoogleARCoreInternal.ARCoreIOSLifecycleManager:_OnARKitFrameUpdated(UnityARCamera)
UnityEngine.XR.iOS.ARFrameUpdate:Invoke(UnityARCamera)
UnityEngine.XR.iOS.ARFrameUpdate:Invoke(UnityARCamera)
UnityEngine.XR.iOS.ARFrameUpdate:Invoke(UnityARCamera)
UnityEngine.XR.iOS.UnityARSessionNativeInterface:_frame_update(internal_UnityARCamera)
`

**Comment by JeanVACCA** [comment]
I have just start a new project ; and it works without any issue.

May be an issue during updates; Sorry for the disturbing.
