### ISSUE TITLE
Google cloud anchors do not resolve on the same device - different session

### ISSUE THREAD

**Issue by Aashwina** [google-ar/arcore-unity-sdk#445]

**Comment by Aashwina** [comment]
I tried the Google cloud anchor on Unity. The anchors are saved and I get a room id , but they are not resolved. I am fairly sure that I am focusing in the right place when I resolve ( I used a variegated mat so should be clean ). I am on wifi ( both my device and my comp ) so the IP address that I get is like so 192.168.0.x  and I am using this to resolve. Is this right ?  Using Unity 2018.x and ARCore 1.4.

**Comment by chaosemer** [comment]
We are improving the Cloud Anchor example in an upcoming release, which should make it much clearer how to do this type of thing.

**Comment by Aashwina** [comment]
Thanks Jared . When can we expect the release?

**Comment by small-potatoes** [comment]
This issue should now be resolved in the [ARCore 1.6 release](https://github.com/google-ar/arcore-unity-sdk/releases).

**Comment by kushal98** [comment]
The issue is still happening in the ARCore 1.6 i am using poco phone and i am facing this issue.

**Comment by RAUNAKKONDIBOYINA** [comment]
I am facing the same issue using poco f1. I don't see a resolve option too

**Comment by marklinmao** [comment]
I also have the same problem with ARCore 1.8. No resolve button, and it doesn't resolve for the same device...

**Comment by chaosemer** [comment]
The sample assumes that you are using Cloud Anchors for a multi-user experience and uses Unity networking to share the cloud anchor ID. If you want to do a persistence-style experience, you will need some other way to share the cloud anchor ID.

See m_CloudAnchorId and CmdSetCloudAnchorId in our example.
