### ISSUE TITLE
Reloading the scene in ARCORE loses the camera access Unity. 

### ISSUE THREAD

**Issue by kharalsuman007** [google-ar/arcore-unity-sdk#61]
Scenario:

Lets says Scene1 in unity uses ARCore camera and you move to scene2 by clicking a button where ARcamera is no longer needed and uses Unity Maincamera. Scene1 works perfectly when you open the app and there is no problem with loading Scene2 but if you try to go to Scene1 again from Scene2 , The app is not using device Camera anymore and the screen is blue. Is this the known issue or you just have to keep the ARCoreDevice gamobject not to be destroyed when loading new scenes.

Note: - I am using SceneManager.LoadScene(levelName, LoadSceneMode.Single); for loading new scenes and my device is Samsung S8 but I guess it has nothing to do this :)

**Comment by chaosemer** [comment]
Thanks for the bug report! We're looking into this.

**Comment by sw-ms-irfankureshi** [comment]
same issue

**Comment by Bakhtiyar86** [comment]
I have the same problem, when will you fix it?)

**Comment by vishalfbs** [comment]
I am also facing same problem. Any help, how to resolve it...

**Comment by chaosemer** [comment]
This is a pretty high priority bug, we're hoping to get a fix into the next release.

**Comment by kharalsuman007** [comment]
Hei , Since you guys are looking for the solution for this problem, You put all the necessary elements needed for AR traction to work on the Empty gameobject , which has a script attached and is responsible for not destroying the gameobject when new scene is loaded .


```
**using System.Collections;
using System.Collections.Generic;
using UnityEngine;
// This script keeps the gameobject not destroyed in case you want same gameobject in different scene
public class DontDestroy : MonoBehaviour {

	// Use this for initialization
	void Awake () 
	{
		DontDestroyOnLoad (this.gameObject);
        // If the same type of gameobject is present in scene already than it is destroyed useful when reloading the same scene
		if (FindObjectsOfType(GetType()).Length > 1)
		{
			Destroy(gameObject);
		}
	}
	
	// Update is called once per frame
	void Update ()
    {
		
	}
}**
```

Be sure to look at screenshot attached.
![arcamera](https://user-images.githubusercontent.com/8639637/35506937-bea2b3a4-04f3-11e8-9bd7-b16506746903.PNG)
 to see how i achieved this. I tagged the empty gameobject as ARcamera , ARcamera has two script Dontdestory and Switchcameraonoff . While don't destory keeps the gameobject , SwithVameraOnOff is script which has public gameobject arCamera , which is "Elements" gameobject. In scenes where you need ARcamera, find the gameobject with tag ARcamera and call the SwitchCameraOnOFF script and enable and disable "Elements" according to your wish. Cheers.

**Comment by chaosemer** [comment]
This has been fixed in ARCore 1.0.

**Comment by scoorey** [comment]
i was using DontDestroyOnLoad in the preview to keep the camera between scenes, but since installing ARCore 1.0, it no longer works

**Comment by scoorey** [comment]
It turns out that in ARCore 1.0 they provide a new prefab called ARCore Device which has session management for it's camera child. If you add DontDestroyOnLoad to the Awake function of the new ARCoreSession script attached to it, you can keep the camera running between scenes. 

I'm not sure how this will integrate with unity's experimental-ARInterface, but at least now I can test my app on ARCore 1.0

Thanks @chaosemer

**Comment by chaosemer** [comment]
Great! I think this issue is resolved then. Please reopen if you have additional issues around the device persisting.

**Comment by mianyaasiraali** [comment]
@chaosemer this issue still exist with ARCore 1.0 . I am using Samsung Galaxy s8  (SM-G950FD). 
what I am trying to achieve is that i want to switch between AR scene(which has ARCORE) and to a non AR scene(which is basically the menu of the game).  
at first it works fine but when I come back to the AR scene from the non ARscene if shows a toast (" ARCore encountered a problem connecting.  Please start the app again.") and the the app crashes.
the "DontDestroyOnLoad()" workaround did not work for me.
would love any kind of help since I'm stuck on it for a couple of days.

**Comment by chaosemer** [comment]
Could you please share a repro project with us? That'll help us know we fixed the issue.

**Comment by pablisho** [comment]
Hi, I cannot repro with the current release [ARCore Unity SDK v1.1.0](https://github.com/google-ar/arcore-unity-sdk/releases/tag/v1.1.0) and the following configuration: one non-AR scene with a regular Unity Camera, one AR Scene with an ARCore Device prefab. I can switch between them without any issue with just SceneManager.LoadScene(0) and SceneManager.LoadScene(1). No DontDestroyOnLoad is needed.
Let me know if this helps, otherwise please tell me what's different in your scenario and a logcat of the issue.

**Comment by aniall-8** [comment]
Just realized that I definitely have an old version of the sdk, I must try to update my project :/  Thanks very much

**Comment by aniall-8** [comment]
Do you know of an easy way to update the sdk?

My project is really big at this point and I'm not full sure how to go
about it, I'm a student.

Thanks either way

**Comment by chaosemer** [comment]
Updating the SDK is simple. Delete the old "GoogleARCore" folder in Unity and re-import the package.

**Comment by pablisho** [comment]
I'm closing this as it's not reproducible with the latest release. Always feel free to reopen if you can still reproduce. In that case please attach logs and a small repro project.
